GROQ_API_KEY = "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"
PAYPAL_CLIENT_ID = "your_paypal_client_id"
PAYPAL_SECRET = "your_paypal_secret"
PAYPAL_MODE = "sandbox"
DOMAIN = "http://localhost:8501"